import type { CodeTok } from '@/components/site/CodeSample';

/** Landing Nu code sample — persistent counter + live UI in one file. */
export const NU_SAMPLE_LINES: CodeTok[][] = [
  [{ c: 'kw', t: 'import' }, { t: ' ' }, { c: 'nu', t: 'nu' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' Counter(' }, { c: 'nu', t: 'nu.Shape' }, { t: '):' }],
  [{ t: '    value: ' }, { c: 'nu', t: 'nu.v.IntRef' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' Dashboard(' }, { c: 'nu', t: 'nu.ui.Page' }, { t: '):' }],
  [{ t: '    count: ' }, { c: 'nu', t: 'nu.ui.TextRef' }],
  [],
  [{ c: 'kw', t: 'class' }, { t: ' App(' }, { c: 'nu', t: 'nu.ui.Index' }, { t: '):' }],
  [{ t: '    pages = ' }, { c: 'nu', t: 'nu.ui.Pages' }, { t: '({' }, { c: 'str', t: '"/"' }, { t: ': Dashboard})' }],
  [],
  [{ t: 'app = ' }, { c: 'nu', t: 'nu.With' }, { t: '(' }],
  [{ t: '    ' }, { c: 'nu', t: 'nu.v.presets.rocksdb_navigator' }, { t: '(' }, { c: 'str', t: '".dbtest"' }, { t: '),' }],
  [{ t: '    ' }, { c: 'nu', t: 'nu.ui.presets.server' }, { t: '(' }],
  [{ t: '        ' }, { c: 'nu', t: 'nu.v.auto_flow_atomic' }, { t: '(' }],
  [{ t: '            ' }, { c: 'nu', t: 'nu.ReactForever' }, { t: '(' }],
  [{ t: '                Counter.value.on_change(),' }],
  [{ t: '                Dashboard.count.set(Counter.value),' }],
  [{ t: '            ),' }],
  [{ t: '        ),' }],
  [{ t: '    ),' }],
  [{ t: '    body=(' }],
  [{ t: '        ' }, { c: 'nu', t: 'nu.IfDo' }, { t: '(Counter.value.missing(), Counter.value.set(0))' }],
  [{ t: '        >> ' }, { c: 'nu', t: 'nu.ForeverDo' }, { t: '(' }],
  [{ t: '            Counter.value.inc() >> ' }, { c: 'nu', t: 'nu.Delay' }, { t: '(1.0),' }],
  [{ t: '        )' }],
  [{ t: '    ),' }],
  [{ t: ')' }],
  [],
  [{ c: 'kw', t: 'if' }, { t: ' __name__ == ' }, { c: 'str', t: "'__main__'" }, { t: ':' }],
  [{ t: '    ' }, { c: 'kw', t: 'import' }, { t: ' asyncio' }],
  [{ t: '    asyncio.run(' }, { c: 'nu', t: 'nu.arun' }, { t: '(' }, { c: 'nu', t: 'nu.v.auto_flow_atomic' }, { t: '(app)))' }],
];
